apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-gorillamux-cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-gorillamux-cassandra
  template:
    metadata:
      labels:
        app: xp-gorillamux-cassandra
    spec:
      containers:
      - name: xp-gorillamux-cassandra
        imagePullPolicy: Never
        image: xp-gorillamux-cassandra:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: xp-gorillamux-cassandra-configmap
        env:
          - name: CASSANDRA_USERNAME
            valueFrom:
              secretKeyRef:
                name: xp-gorillamux-cassandra-secrets
                key: CASSANDRA_USERNAME
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: xp-gorillamux-cassandra-secrets
                key: CASSANDRA_PASSWORD
