apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-gorillamux-cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-gorillamux-cassandra
  template:
    metadata:
      labels:
        app: xp-gorillamux-cassandra
    spec:
      containers:
      - name: xp-gorillamux-cassandra
        imagePullPolicy: Never
        image: xp-gorillamux-cassandra:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: xp-gorillamux-cassandra-configmap
        env:
          - name: CASSANDRA_USERNAME
            valueFrom:
              secretKeyRef:
                name: xp-gorillamux-cassandra-secrets
                key: CASSANDRA_USERNAME
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: xp-gorillamux-cassandra-secrets
                key: CASSANDRA_PASSWORD
          # This given to us from Helm chart
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: xp-redis
                key: redis-password
          - name: KAFKA_SASL_USERNAME
            valueFrom:
              secretKeyRef:
                name: xp-gorillamux-cassandra-secrets
                key: KAFKA_SASL_USERNAME
          # This given to us from Helm chart
          - name: KAFKA_SASL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: xp-kafka-user-passwords
                key: client-passwords
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
