apiVersion: v1
kind: Service
metadata:
  name: xp-gorillamux-cassandra-service
spec:
  selector:
    app: xp-gorillamux-cassandra
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer